services:
  app:
    image: node:18-alpine
    build: .
    container_name: docker-teste
    command: sh -c "npm i && npm start"
    ports:
      - 8081:8081
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
